trigger:
- uat_infra  # Adjust to your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.4.6'  # Update to the desired Terraform version
  - group: TerraformSecretsDev

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    steps:
    - task: UseTerraform@0
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        cd Infra_deployment
        terraform init
      displayName: 'Terraform Init'

    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
