FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8002

ENV UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 8002 --reload"

CMD ["sh", "-c", "$UVICORN_CMD"]
